data.raw.container["wooden-chest"].inventory_size = 27
data.raw.container["wooden-chest"].picture.layers[1].filename = "__wide-steel-chests__/graphics/easter-egg/minecraft-chest.png"
data.raw["item"]["wooden-chest"].icon = nil
data.raw["item"]["wooden-chest"].icons = {{}}
data.raw["item"]["wooden-chest"].icons[1].icon = "__wide-steel-chests__/graphics/easter-egg/icons/minecraft-chest.png"
data.raw["item"]["wooden-chest"].icons[1].icon_size = 128
data.raw["recipe"]["wooden-chest"].icon = nil
data.raw["recipe"]["wooden-chest"].icons = {{}}
data.raw["recipe"]["wooden-chest"].icons[1].icon = "__wide-steel-chests__/graphics/easter-egg/icons/minecraft-chest.png"
data.raw["recipe"]["wooden-chest"].icons[1].icon_size = 128
data.raw["container"]["wooden-chest"].icon = nil
data.raw["container"]["wooden-chest"].icons = {{}}
data.raw["container"]["wooden-chest"].icons[1].icon = "__wide-steel-chests__/graphics/easter-egg/icons/minecraft-chest.png"
data.raw["container"]["wooden-chest"].icons[1].icon_size = 128
data.raw.container["wooden-chest"].picture.layers[1].width=64
data.raw.container["wooden-chest"].picture.layers[1].height=64
data.raw.container["wooden-chest"].picture.layers[1].shift = util.by_pixel(0, 0)
data.raw.container["wooden-chest"].open_sound.filename = "__wide-steel-chests__/sound/easter-egg/chestopen.ogg"
data.raw.container["wooden-chest"].close_sound.filename = "__wide-steel-chests__/sound/easter-egg/chestclosed.ogg"

data.raw.container["wooden-chest"].inventory_size = 54
data.raw.container["wide-wooden-chest"].picture.layers[1].filename = "__wide-steel-chests__/graphics/easter-egg/minecraft-wide-chest.png"
data.raw["item"]["wide-wooden-chest"].icons[1].icon = "__wide-steel-chests__/graphics/easter-egg/icons/minecraft-wide-chest.png"
data.raw["recipe"]["wide-wooden-chest"].icons[1].icon = "__wide-steel-chests__/graphics/easter-egg/icons/minecraft-wide-chest.png"
data.raw.container["wide-wooden-chest"].picture.layers[1].width=128
data.raw.container["wide-wooden-chest"].picture.layers[1].height=64
data.raw.container["wide-wooden-chest"].picture.layers[1].shift = util.by_pixel(0, 0)
data.raw.container["wide-wooden-chest"].open_sound.filename = "__wide-steel-chests__/sound/easter-egg/chestopen.ogg"
data.raw.container["wide-wooden-chest"].close_sound.filename = "__wide-steel-chests__/sound/easter-egg/chestclosed.ogg"
data.raw["technology"]["wide-containers"].icons[1].icon = "__wide-steel-chests__/graphics/easter-egg/icons/minecraft-wide-chest.png"